name: "Build asset"
description: "Build the asset required for deployment"

runs:
  using: "composite"
  steps:
    # Convert /bin/sh to /bin/bash.
    - name: Setup Node.js 14.12.0
      uses: actions/setup-node@v1
      with:
        node-version: "14.12.0"
    - uses: actions/cache@v2
      with:
        path: ~/.npm
        key: node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          node-
    - name: "Setup node dependencies"
      uses: ./.github/actions/setup-node-deps
    - name: "Build asset"
      uses: ./.github/actions/build-asset
    - uses: actions/upload-artifact@v2
      with:
        name: bootstrap
        path: ./target/cdk/release/bootstrap
        if-no-files-found: error
