name: release

# Refer to https://help.github.com/en/articles/workflow-syntax-for-github-actions for documentation on Actions.
on:
  release:
    types:
      - released

jobs:
  # Generate a static build artifact for usage in deployments.
  assets:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js 14.12.0
        uses: actions/setup-node@v1
        with:
          node-version: "14.12.0"
      - name: "Install dependencies"
        run: |
          cd /home/runner/work/cloud-serverless-url-shortener
          npm ci
      - name: "Build asset"
        run: |
          npm run build
          mkdir -p dist/lib/website
          cp lib/website/index.html dist/lib/website/index.html
      - name: Compress action step
        uses: master-atul/tar-action@v1.0.2
        id: compress
        with:
          command: c
          files: |
            /home/runner/work/cloud-serverless-url-shortener/dist
          outPath: build.tar.gz
      - uses: actions/upload-artifact@v2
        with:
          name: tsbuild.tar.gz
          path: ./build.tar.gz
          if-no-files-found: error

      - name: Deploy
        if: env.AWS_ACCESS_KEY_ID && env.AWS_SECRET_ACCESS_KEY
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.RELEASE_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.RELEASE_AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.RELEASE_AWS_REGION }}
          CI: "true"
        run: |
          npm run cdk:deploy
